"""Plot the parallel-shear spectrum shown in Figure 4.

The script reads the data generated by ``compute_eigenanalysis.py`` and does
not solve the eigenvalue problem.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib as mpl

mpl.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
import numpy as np


CODE_ROOT = Path(__file__).resolve().parents[1]
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))

from common.spectrum_plotting import (  # noqa: E402
    add_ratio_colorbar,
    load_spectrum_colormap as load_colormap,
    save_spectrum_figure,
    spectrum_publication_style as publication_style,
)

FONT_SIZE = 10
DEFAULT_INPUT = (
    Path(__file__).resolve().parent / "data" / "parallel_shear_eigenanalysis.npz"
)
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "figures" / "parallel_shear_spectrum"
DEFAULT_COLORMAP = (
    Path(__file__).resolve().parent.parent / "common" / "custom_gradient_32_to_256.mat"
)


def plot_spectrum(
    along_stream_rows: np.ndarray,
    vertical_mode_rows: np.ndarray,
    output_stem: Path,
    *,
    colormap_path: Path,
    frequency_min: float,
    frequency_max: float,
    ratio_min: float,
    ratio_max: float,
    fixed_vertical_mode: int,
    use_tex: bool,
) -> None:
    """Create the two-panel spectrum figure."""
    line_frequency_max = max(frequency_max, 1.2)
    along_stream_data = along_stream_rows[
        (along_stream_rows[:, 2] >= frequency_min)
        & (along_stream_rows[:, 2] <= line_frequency_max)
    ]
    vertical_mode_data = vertical_mode_rows[
        (vertical_mode_rows[:, 2] >= frequency_min)
        & (vertical_mode_rows[:, 2] <= frequency_max)
    ]

    scale = 0.8
    with plt.rc_context(publication_style(use_tex=use_tex)):
        figure = plt.figure(figsize=(5.6 * scale, 4.3 * scale))
        colorbar_axis = figure.add_axes((0.905, 0.15, 0.014, 0.72))
        vertical_axis = figure.add_axes((0.16, 0.58, 0.72, 0.34))
        wavenumber_axis = figure.add_axes((0.16, 0.10, 0.72, 0.34))

        colormap = load_colormap(colormap_path)
        normalization = mpl.colors.Normalize(
            vmin=ratio_min,
            vmax=ratio_max,
        )

        for branch in np.unique(along_stream_data[:, 1]).astype(int):
            branch_data = along_stream_data[along_stream_data[:, 1] == branch]
            if branch_data.shape[0] < 2:
                continue
            branch_data = branch_data[np.argsort(branch_data[:, 0])]
            points = branch_data[:, [0, 2]].reshape(-1, 1, 2)
            segments = np.concatenate([points[:-1], points[1:]], axis=1)
            values = 0.5 * (branch_data[:-1, 5] + branch_data[1:, 5])
            collection = LineCollection(
                segments,
                colors=colormap(normalization(values)),
                linewidths=1.32 * scale,
                antialiaseds=True,
                rasterized=False,
                zorder=2,
            )
            collection.set_capstyle("projecting")
            wavenumber_axis.add_collection(collection)

        wavenumber_axis.axhline(
            0.0,
            color="0.55",
            linewidth=0.7 * scale,
            zorder=0,
        )
        wavenumber_axis.axvline(
            0.0,
            color="0.25",
            linewidth=0.8 * scale,
            linestyle="--",
            zorder=0.2,
        )
        wavenumber_limits = (
            along_stream_rows[:, 0].min(),
            along_stream_rows[:, 0].max(),
        )
        wavenumber_axis.set_xlim(*wavenumber_limits)
        wavenumber_axis.set_ylim(frequency_min, frequency_max)
        wavenumber_axis.set_yticks(np.arange(frequency_min, frequency_max + 0.1, 0.2))
        ticks = [
            tick
            for tick in [-3, -2, -1, 0, 1, 2, 3]
            if wavenumber_limits[0] <= tick <= wavenumber_limits[1]
        ]
        wavenumber_axis.set_xticks(ticks)
        wavenumber_axis.set_xticklabels([rf"${tick}$" for tick in ticks])
        wavenumber_axis.set_xlabel(r"$k_yL$")
        wavenumber_axis.set_ylabel(r"$\omega/f$")
        wavenumber_axis.text(
            -0.135,
            1.025,
            r"$(b)$",
            transform=wavenumber_axis.transAxes,
            ha="left",
            va="bottom",
            clip_on=False,
        )

        selected = vertical_mode_data[
            np.isclose(vertical_mode_data[:, 0], fixed_vertical_mode)
        ]
        wavenumber_axis.scatter(
            np.zeros_like(selected[:, 2]),
            selected[:, 2],
            c=selected[:, 5],
            s=15.0 * scale**2,
            linewidths=0.4 * scale,
            edgecolors="black",
            cmap=colormap,
            norm=normalization,
            zorder=5,
            clip_on=True,
        )

        label_position = 0.45
        branch_labels: list[float] = []
        for branch in np.unique(along_stream_data[:, 1]).astype(int):
            branch_data = along_stream_data[along_stream_data[:, 1] == branch]
            branch_data = branch_data[np.argsort(branch_data[:, 0])]
            if (
                branch_data.shape[0] >= 2
                and branch_data[0, 0] <= label_position <= branch_data[-1, 0]
            ):
                frequency = np.interp(
                    label_position,
                    branch_data[:, 0],
                    branch_data[:, 2],
                )
                if frequency_min <= frequency <= frequency_max:
                    branch_labels.append(float(frequency))

        label_offsets = {"I": -0.02, "II": -0.02, "III": 0.005}
        for frequency, label in zip(
            sorted(branch_labels)[:3],
            ["I", "II", "III"],
        ):
            wavenumber_axis.text(
                label_position,
                frequency + label_offsets[label],
                rf"$\mathrm{{{label}}}$",
                ha="center",
                va="center",
                color="black",
                fontsize=FONT_SIZE * scale * 0.75,
                zorder=6,
                clip_on=True,
            )

        outlined = np.zeros(vertical_mode_data.shape[0], dtype=bool)
        for vertical_mode in np.unique(vertical_mode_data[:, 0]):
            indices = np.flatnonzero(
                np.isclose(vertical_mode_data[:, 0], vertical_mode)
            )
            lowest = indices[np.argsort(vertical_mode_data[indices, 2])[:5]]
            outlined[lowest] = True

        faded = vertical_mode_data[~outlined]
        faded = faded[np.argsort(faded[:, 2])[::-1]]
        vertical_axis.scatter(
            faded[:, 0],
            faded[:, 2],
            c=faded[:, 5],
            s=12.5 * scale**2,
            linewidths=0.0,
            edgecolors="none",
            cmap=colormap,
            norm=normalization,
            alpha=0.16,
            rasterized=True,
        )
        highlighted = vertical_mode_data[outlined]
        highlighted = highlighted[np.argsort(highlighted[:, 2])[::-1]]
        vertical_axis.scatter(
            highlighted[:, 0],
            highlighted[:, 2],
            c=highlighted[:, 5],
            s=12.5 * scale**2,
            linewidths=0.35 * scale,
            edgecolors="black",
            cmap=colormap,
            norm=normalization,
            rasterized=True,
            zorder=5,
        )
        vertical_axis.axhline(
            0.0,
            color="0.55",
            linewidth=0.7 * scale,
            zorder=0,
        )
        vertical_axis.axvline(
            fixed_vertical_mode,
            color="0.25",
            linewidth=0.8 * scale,
            linestyle="--",
            zorder=0.2,
        )
        vertical_axis.set_xlim(0.4, 32.6)
        vertical_axis.set_ylim(frequency_min, frequency_max)
        vertical_axis.set_yticks(np.arange(frequency_min, frequency_max + 0.1, 0.2))
        maximum_tick = 4 * int(np.ceil(vertical_mode_rows[:, 0].max() / 4))
        mode_ticks = np.r_[0, 1, np.arange(4, maximum_tick + 1, 4)]
        vertical_axis.set_xticks(mode_ticks)
        vertical_axis.set_xticklabels([""] + [rf"${tick}$" for tick in mode_ticks[1:]])
        vertical_axis.set_xlim(0.4, 32.6)
        vertical_axis.set_xlabel(r"Integer wavenumber $n$")
        vertical_axis.set_ylabel(r"$\omega/f$")
        vertical_axis.text(
            -0.135,
            1.025,
            r"$(a)$",
            transform=vertical_axis.transAxes,
            ha="left",
            va="bottom",
            clip_on=False,
        )

        add_ratio_colorbar(
            figure,
            colorbar_axis,
            normalization=normalization,
            colormap=colormap,
            ratio_min=ratio_min,
            ratio_max=ratio_max,
            scale=scale,
        )
        save_spectrum_figure(figure, output_stem)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Plot the parallel-shear eigenvalue spectrum."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--colormap", type=Path, default=DEFAULT_COLORMAP)
    parser.add_argument("--frequency-min", type=float, default=-0.2)
    parser.add_argument("--frequency-max", type=float, default=1.0)
    parser.add_argument("--ratio-min", type=float, default=0.0)
    parser.add_argument("--ratio-max", type=float, default=0.4)
    parser.add_argument("--fixed-vertical-mode", type=int, default=4)
    parser.add_argument("--no-tex", action="store_true")
    return parser.parse_args()


def main() -> None:
    """Load the computed data and create the spectrum figure."""
    args = parse_args()
    with np.load(args.input) as data:
        along_stream_rows = data["along_stream_spectrum"]
        vertical_mode_rows = data["vertical_mode_spectrum"]
    plot_spectrum(
        along_stream_rows,
        vertical_mode_rows,
        args.output,
        colormap_path=args.colormap,
        frequency_min=args.frequency_min,
        frequency_max=args.frequency_max,
        ratio_min=args.ratio_min,
        ratio_max=args.ratio_max,
        fixed_vertical_mode=args.fixed_vertical_mode,
        use_tex=not args.no_tex,
    )
    print(args.output.with_suffix(".png"))
    print(args.output.with_suffix(".pdf"))


if __name__ == "__main__":
    main()
