"""Plot the parallel-shear eigenfunctions shown in Figure 5.

The script reads phase-aligned eigenfunctions from the data file generated by
``compute_eigenanalysis.py`` and performs no eigensystem calculation.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib as mpl

mpl.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.colors import LinearSegmentedColormap
import numpy as np


CORIOLIS_FREQUENCY = 1.0e-4
TEXT_WIDTH_INCHES = 5.60
FONT_SIZE = 14

DEFAULT_INPUT = (
    Path(__file__).resolve().parent / "data" / "parallel_shear_eigenanalysis.npz"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent / "figures" / "parallel_shear_eigenfunctions"
)


def publication_style(*, use_tex: bool) -> dict[str, object]:
    """Return the typography used for the published eigenfunction figure."""
    style: dict[str, object] = {
        "font.family": "serif",
        "font.size": FONT_SIZE,
        "axes.labelsize": FONT_SIZE,
        "axes.titlesize": FONT_SIZE,
        "axes.linewidth": 1.3,
        "axes.unicode_minus": False,
        "axes.grid": False,
        "xtick.labelsize": FONT_SIZE,
        "ytick.labelsize": FONT_SIZE,
        "xtick.direction": "out",
        "ytick.direction": "out",
        "xtick.top": False,
        "ytick.right": False,
        "xtick.major.size": 3.0,
        "ytick.major.size": 3.0,
        "xtick.major.width": 1.1,
        "ytick.major.width": 1.1,
        "xtick.minor.visible": False,
        "ytick.minor.visible": False,
        "lines.linewidth": 1.0,
        "legend.fontsize": FONT_SIZE,
        "savefig.dpi": 600,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,
        "savefig.transparent": False,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
    if use_tex:
        style.update(
            {
                "text.usetex": True,
                "text.latex.preamble": (
                    r"\usepackage{amsmath}"
                    r"\usepackage{newtxtext}"
                    r"\usepackage{newtxmath}"
                ),
            }
        )
    else:
        style.update({"text.usetex": False, "mathtext.fontset": "stix"})
    return style


def format_axis(axis: mpl.axes.Axes, ylabel: str) -> None:
    """Apply the common axis formatting to one eigenfunction panel."""
    axis.set_ylabel(ylabel, fontsize=FONT_SIZE - 1)
    axis.minorticks_off()
    axis.xaxis.set_minor_locator(ticker.NullLocator())
    axis.yaxis.set_minor_locator(ticker.NullLocator())
    axis.yaxis.set_major_locator(ticker.FixedLocator([-1.0, 0.0, 1.0]))
    axis.yaxis.set_major_formatter(ticker.FixedFormatter([r"$-1$", r"$0$", r"$1$"]))
    axis.yaxis.tick_left()
    axis.tick_params(
        axis="x",
        which="major",
        direction="out",
        top=False,
        bottom=True,
    )
    axis.tick_params(
        axis="y",
        which="major",
        direction="out",
        left=True,
        right=False,
        labelleft=True,
        labelright=False,
        pad=1,
    )
    axis.yaxis.set_label_position("left")
    axis.yaxis.set_label_coords(-0.045, 0.5)
    for spine in axis.spines.values():
        spine.set_linewidth(1.3)
        spine.set_zorder(10)


def plot_eigenfunctions(
    coordinate: np.ndarray,
    wavenumbers: np.ndarray,
    component_up: np.ndarray,
    component_down: np.ndarray,
    frequencies: np.ndarray,
    output_stem: Path,
    *,
    use_tex: bool,
) -> None:
    """Create the three-panel eigenfunction overlay."""
    panel_count = component_up.shape[1]
    branch_labels = [
        r"Branch $\mathrm{I}$",
        r"Branch $\mathrm{II}$",
        r"Branch $\mathrm{III}$",
        r"Branch $\mathrm{IV}$",
        r"Branch $\mathrm{V}$",
    ]
    frequency_labels = []
    for panel_index in range(panel_count):
        values = frequencies[:, panel_index].real / CORIOLIS_FREQUENCY
        frequency_labels.append(
            rf"$\omega \in [{values.min():5.2f},{values.max():5.2f}]f$"
        )

    blue_map = LinearSegmentedColormap.from_list(
        "reference_blue",
        ["#c9d9ea", "#356ecf", "#12327f"],
    )
    red_map = LinearSegmentedColormap.from_list(
        "reference_red",
        ["#ead0c9", "#cf5635", "#7f1232"],
    )
    denominator = max(wavenumbers.size - 1, 1)
    blue_colors = [blue_map(index / denominator) for index in range(wavenumbers.size)]
    red_colors = [red_map(index / denominator) for index in range(wavenumbers.size)]

    with plt.rc_context(publication_style(use_tex=use_tex)):
        figure = plt.figure(figsize=(TEXT_WIDTH_INCHES, TEXT_WIDTH_INCHES * 0.95))
        grid = figure.add_gridspec(
            panel_count,
            1,
            left=0.12,
            right=0.88,
            bottom=0.09,
            top=0.89,
            hspace=0.22,
        )
        axes = np.array(
            [figure.add_subplot(grid[index, 0]) for index in range(panel_count)]
        )

        for panel_index, axis in enumerate(axes):
            display_sign = -1.0 if panel_index == 1 else 1.0
            for wavenumber_index in range(wavenumbers.size):
                axis.plot(
                    coordinate,
                    display_sign * component_up[wavenumber_index, panel_index],
                    color=blue_colors[wavenumber_index],
                    linewidth=1.1,
                    zorder=3,
                    clip_on=True,
                )
            for wavenumber_index in range(wavenumbers.size):
                axis.plot(
                    coordinate,
                    display_sign * component_down[wavenumber_index, panel_index],
                    color=red_colors[wavenumber_index],
                    linewidth=1.0,
                    zorder=4,
                    clip_on=True,
                )

            axis.axhline(0.0, color="0.45", linewidth=1.1, zorder=0)
            axis.set_xlim(-np.pi, np.pi)
            axis.set_ylim(-1.08, 1.08)
            axis.set_xticks([-np.pi, 0.0, np.pi])
            axis.text(
                -0.145,
                1.04,
                rf"(${chr(ord('a') + panel_index)}$)",
                transform=axis.transAxes,
                ha="left",
                va="top",
                fontsize=FONT_SIZE,
                clip_on=False,
            )
            axis.text(
                0.02,
                0.04,
                frequency_labels[panel_index],
                transform=axis.transAxes,
                ha="left",
                va="bottom",
                fontsize=FONT_SIZE - 2,
            )
            label = (
                branch_labels[panel_index]
                if panel_index < len(branch_labels)
                else rf"Branch {panel_index + 1}"
            )
            format_axis(axis, label)

        for axis in axes[:-1]:
            axis.tick_params(labelbottom=False)
        axes[-1].set_xticklabels([r"$-\pi$", r"$x/L$", r"$\pi$"])

        # The invisible marker keeps the tight export horizontally balanced.
        figure.text(
            0.990,
            0.5,
            ".",
            color="white",
            fontsize=1,
            ha="left",
            va="center",
        )

        output_stem.parent.mkdir(parents=True, exist_ok=True)
        figure.savefig(
            output_stem.with_suffix(".pdf"),
            bbox_inches="tight",
            pad_inches=0.02,
        )
        figure.savefig(
            output_stem.with_suffix(".png"),
            dpi=600,
            bbox_inches="tight",
            pad_inches=0.02,
        )
        plt.close(figure)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Plot the parallel-shear eigenfunction overlays."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--no-tex", action="store_true")
    return parser.parse_args()


def main() -> None:
    """Load the computed modes and create the eigenfunction figure."""
    args = parse_args()
    with np.load(args.input) as data:
        coordinate = data["overlay_coordinate"]
        wavenumbers = data["overlay_wavenumbers"]
        component_up = data["overlay_component_up"]
        component_down = data["overlay_component_down"]
        frequencies = data["overlay_frequencies"]
    plot_eigenfunctions(
        coordinate,
        wavenumbers,
        component_up,
        component_down,
        frequencies,
        args.output,
        use_tex=not args.no_tex,
    )
    print(args.output.with_suffix(".png"))
    print(args.output.with_suffix(".pdf"))


if __name__ == "__main__":
    main()
