"""Prepare the solver-generated fields plotted in Figures 9 and 10."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import h5py
import numpy as np

from specification import MODEL_NAMES

DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent
    / "data"
    / "sinusoidal_dipole_wave_velocity_fields.npz"
)
VERTICAL_MODES = (1, 4, 8, 16, 32)
TARGET_TIMES = (10.0, 50.0)


def exact_indices(available: np.ndarray, requested: tuple[float, ...]) -> list[int]:
    indices: list[int] = []
    for target in requested:
        matches = np.flatnonzero(np.isclose(available, target, rtol=0.0, atol=1e-12))
        if matches.size != 1:
            raise ValueError(f"The exact saved state at {target:g} IP is unavailable.")
        indices.append(int(matches[0]))
    return indices


def compute_fields(
    simulation_path: Path,
    target_times: tuple[float, ...] = TARGET_TIMES,
) -> dict[str, np.ndarray]:
    """Read physical velocities generated by the in-repository solver."""
    fields_by_mode: list[np.ndarray] = []
    wavelengths: list[float] = []
    with h5py.File(simulation_path, "r") as handle:
        stored_names = tuple(json.loads(handle.attrs["model_names"]))
        if stored_names != MODEL_NAMES:
            raise ValueError(f"Unexpected model order: {stored_names}.")
        config = json.loads(handle.attrs["config_json"])
        amplitude = float(
            config["physical_parameters"]["initial_velocity_amplitude_m_s"]
        )
        for mode in VERTICAL_MODES:
            group = handle[f"modes/n{mode:04d}"]
            available = np.asarray(group["field_times_ip"])
            indices = exact_indices(available, target_times)
            velocity = np.asarray(group["complex_velocity"])[indices]
            fields_by_mode.append(np.abs(velocity) ** 2 / amplitude**2)
            wavelengths.append(float(group.attrs["vertical_wavelength_m"]))

    squared_velocity = np.stack(fields_by_mode, axis=1)
    return {
        "times_in_inertial_periods": np.asarray(target_times, dtype=float),
        "vertical_modes": np.asarray(VERTICAL_MODES, dtype=int),
        "vertical_wavelengths_m": np.asarray(wavelengths),
        "model_names": np.asarray(MODEL_NAMES),
        "squared_velocity": squared_velocity,
        "source_files": np.asarray([simulation_path.name] * len(VERTICAL_MODES)),
    }


def parse_float_list(value: str) -> tuple[float, ...]:
    values = tuple(float(item.strip()) for item in value.split(",") if item.strip())
    if not values:
        raise argparse.ArgumentTypeError("At least one time is required.")
    return values


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--times", type=parse_float_list, default=TARGET_TIMES)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    results = compute_fields(args.input, args.times)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(args.output, **results)
    print(args.output)


if __name__ == "__main__":
    main()
