"""Plot the sinusoidal-dipole fields shown in Figures 9 and 10.

The script reads normalized squared velocity fields generated by
``compute_wave_velocity_fields.py`` and performs no simulation-data loading.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib as mpl

mpl.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from matplotlib.transforms import Bbox, ScaledTranslation
import numpy as np

from specification import load_reference_metrics


DEFAULT_INPUT = (
    Path(__file__).resolve().parent
    / "data"
    / "sinusoidal_dipole_wave_velocity_fields.npz"
)
DEFAULT_OUTPUT_DIRECTORY = Path(__file__).resolve().parent / "figures"
REFERENCE_METRICS = load_reference_metrics()
PUBLISHED_N4_T50_LIMITS = tuple(
    REFERENCE_METRICS["movie2"]["absolute_color_limits"]["4"]
)
FIGURE_WIDTH_INCHES = 330.24 / 72.0
PAGE_HEIGHT_INCHES = 267.44 / 72.0
LAYOUT_SCALE = FIGURE_WIDTH_INCHES / 7.15
BOTTOM_CROP_INCHES = 0.12 * (PAGE_HEIGHT_INCHES / 6.18)
FIGURE_HEIGHT_INCHES = PAGE_HEIGHT_INCHES + BOTTOM_CROP_INCHES


def publication_style(*, use_tex: bool) -> dict[str, object]:
    """Return the typography used for the wave-velocity montages."""
    style: dict[str, object] = {
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "savefig.facecolor": "white",
        "font.family": "serif",
        "font.size": 9.0 * LAYOUT_SCALE,
        "axes.labelsize": 9.0 * LAYOUT_SCALE,
        "axes.titlesize": 9.0 * LAYOUT_SCALE,
        "xtick.labelsize": 9.0 * LAYOUT_SCALE,
        "ytick.labelsize": 9.0 * LAYOUT_SCALE,
        "axes.linewidth": 0.6,
        "xtick.direction": "out",
        "ytick.direction": "out",
        "xtick.major.size": 3.0 * LAYOUT_SCALE,
        "ytick.major.size": 3.0 * LAYOUT_SCALE,
        "xtick.major.width": 0.6,
        "ytick.major.width": 0.6,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
    if use_tex:
        style.update(
            {
                "text.usetex": True,
                "text.latex.preamble": (
                    r"\usepackage{newtxtext}"
                    r"\usepackage{newtxmath}"
                ),
            }
        )
    else:
        style.update({"text.usetex": False, "mathtext.fontset": "stix"})
    return style


def outward_significant(
    value: float,
    digits: int,
    *,
    upward: bool,
) -> float:
    """Round a positive color limit outward to fixed significant digits."""
    if value == 0.0:
        return 0.0
    scale = 10.0 ** (digits - 1 - np.floor(np.log10(abs(value))))
    rounded = np.ceil(value * scale) if upward else np.floor(value * scale)
    return float(rounded / scale)


def colorbar_tick_label(value: float) -> str:
    """Format colorbar ticks while retaining two decimals below one."""
    if np.isclose(value, 1.0):
        return "1.00"
    if abs(value) < 1.0:
        return f"{value:.2f}"
    return f"{value:.2f}".rstrip("0").rstrip(".")


def row_color_limits(
    fields: np.ndarray,
    *,
    target_time: float,
    vertical_mode: int,
) -> tuple[float, float, bool]:
    """Return the robust linear limits used for one vertical-mode row."""
    finite = fields[np.isfinite(fields)]
    raw_minimum, raw_maximum = np.quantile(
        finite,
        (0.005, 0.995),
    )
    raw_minimum = outward_significant(
        float(raw_minimum),
        3,
        upward=False,
    )
    raw_maximum = outward_significant(
        float(raw_maximum),
        3,
        upward=True,
    )
    half_width = max(1.0 - raw_minimum, raw_maximum - 1.0)
    centered_minimum = 1.0 - half_width
    if centered_minimum >= 0.01:
        minimum = centered_minimum
        maximum = 1.0 + half_width
        centered_on_one = True
    else:
        minimum = max(raw_minimum, 0.01)
        maximum = raw_maximum
        centered_on_one = False

    # The n=4 row at 50 IP uses the fixed published range.
    if np.isclose(target_time, 50.0) and vertical_mode == 4:
        minimum, maximum = PUBLISHED_N4_T50_LIMITS
        centered_on_one = False
    return minimum, maximum, centered_on_one


def row_color_metadata(
    fields: np.ndarray,
    model_names: np.ndarray,
    *,
    target_time: float,
    vertical_mode: int,
    minimum: float,
    maximum: float,
    centered_on_one: bool,
) -> dict[str, object]:
    """Describe plotted limits, extrema and any clipped samples."""
    finite = fields[np.isfinite(fields)]
    if fields.ndim != 3 or fields.shape[0] != model_names.size:
        raise ValueError("One two-dimensional field is required for each model.")
    if finite.size != fields.size:
        raise ValueError("Wave-velocity fields must contain only finite values.")
    sample_count = int(finite.size)
    below_count = int(np.count_nonzero(finite < minimum))
    above_count = int(np.count_nonzero(finite > maximum))
    model_extrema = {
        str(model_name): {
            "minimum": float(np.min(model_field)),
            "maximum": float(np.max(model_field)),
        }
        for model_name, model_field in zip(model_names, fields, strict=True)
    }
    return {
        "vertical_mode": vertical_mode,
        "color_limits": [minimum, maximum],
        "centered_on_one": centered_on_one,
        "fixed_published_override": bool(
            np.isclose(target_time, 50.0) and vertical_mode == 4
        ),
        "sample_count": sample_count,
        "field_minimum": float(np.min(finite)),
        "field_maximum": float(np.max(finite)),
        "below_color_limit_count": below_count,
        "above_color_limit_count": above_count,
        "below_color_limit_fraction": below_count / sample_count,
        "above_color_limit_fraction": above_count / sample_count,
        "model_extrema": model_extrema,
    }


def position_square_axes(
    figure: mpl.figure.Figure,
    axes: np.ndarray,
) -> None:
    """Place all field panels on a compact grid of equal squares."""
    row_count, column_count = axes.shape
    left, right, bottom, top = 0.13, 0.84, 0.10, 0.95
    gap_inches = 0.13 * min(LAYOUT_SCALE, PAGE_HEIGHT_INCHES / 6.18)
    figure_width, figure_height = figure.get_size_inches()
    side_inches = min(
        (figure_width * (right - left) - (column_count - 1) * gap_inches)
        / column_count,
        (figure_height * (top - bottom) - (row_count - 1) * gap_inches) / row_count,
    )
    side_width = side_inches / figure_width
    side_height = side_inches / figure_height
    gap_x = gap_inches / figure_width
    gap_y = gap_inches / figure_height
    total_width = column_count * side_width + (column_count - 1) * gap_x
    total_height = row_count * side_height + (row_count - 1) * gap_y
    start_x = left + ((right - left) - total_width) / 2.0
    start_y = bottom + ((top - bottom) - total_height) / 2.0

    for row in range(row_count):
        for column in range(column_count):
            position_x = start_x + column * (side_width + gap_x)
            position_y = start_y + (row_count - 1 - row) * (side_height + gap_y)
            axes[row, column].set_position(
                (position_x, position_y, side_width, side_height)
            )


def plot_snapshot(
    fields: np.ndarray,
    vertical_modes: np.ndarray,
    model_names: np.ndarray,
    target_time: float,
    output_stem: Path,
    *,
    colormap_name: str,
    use_tex: bool,
) -> None:
    """Create one five-row, five-column wave-velocity montage."""
    with plt.rc_context(publication_style(use_tex=use_tex)):
        figure, axes = plt.subplots(
            vertical_modes.size,
            model_names.size,
            figsize=(FIGURE_WIDTH_INCHES, FIGURE_HEIGHT_INCHES),
            squeeze=False,
            constrained_layout=False,
        )
        position_square_axes(figure, axes)
        extent = (-np.pi, np.pi, -np.pi, np.pi)
        row_images: list[
            tuple[
                mpl.image.AxesImage,
                float,
                float,
                bool,
                int,
            ]
        ] = []
        color_rows: list[dict[str, object]] = []

        for row_index, vertical_mode in enumerate(vertical_modes):
            minimum, maximum, centered_on_one = row_color_limits(
                fields[row_index],
                target_time=target_time,
                vertical_mode=int(vertical_mode),
            )
            color_rows.append(
                row_color_metadata(
                    fields[row_index],
                    model_names,
                    target_time=target_time,
                    vertical_mode=int(vertical_mode),
                    minimum=minimum,
                    maximum=maximum,
                    centered_on_one=centered_on_one,
                )
            )
            image: mpl.image.AxesImage | None = None
            for column_index, model_name in enumerate(model_names):
                axis = axes[row_index, column_index]
                image = axis.imshow(
                    fields[row_index, column_index],
                    origin="lower",
                    extent=extent,
                    aspect="equal",
                    interpolation="nearest",
                    cmap=colormap_name,
                    vmin=minimum,
                    vmax=maximum,
                )
                for spine in axis.spines.values():
                    spine.set_linewidth(1.0)
                    spine.set_zorder(10)
                axis.set_xticks((-np.pi, 0.0, np.pi))
                axis.set_yticks((-np.pi, 0.0, np.pi))
                axis.xaxis.set_ticks_position("bottom")
                axis.yaxis.set_ticks_position("right")
                axis.tick_params(
                    axis="both",
                    length=3.0,
                    width=0.8,
                    pad=1.8,
                )
                axis.set_xticklabels(())
                axis.set_yticklabels(())

                if row_index == 0:
                    display_name = (
                        r"YBJ$^{+}$" if model_name == "YBJ+" else str(model_name)
                    )
                    axis.set_title(
                        display_name,
                        pad=3.5 * LAYOUT_SCALE,
                        fontsize=12.0 * LAYOUT_SCALE,
                    )
                if column_index == 0:
                    row_label = (
                        rf"$n={vertical_mode}$"
                        if vertical_mode == 1
                        else rf"${vertical_mode}$"
                    )
                    axis.text(
                        -0.14,
                        0.5,
                        row_label,
                        transform=axis.transAxes,
                        ha="right",
                        va="center",
                        fontsize=14.0 * LAYOUT_SCALE,
                    )
                if row_index == vertical_modes.size - 1:
                    axis.set_xticklabels((r"$-\pi$", r"$x/L$", r"$\pi$"))
                    labels = axis.get_xticklabels()
                    labels[0].set_horizontalalignment("left")
                    labels[2].set_horizontalalignment("right")
                    labels[1].set_fontsize(9.0 * LAYOUT_SCALE)
                if column_index == model_names.size - 1:
                    axis.yaxis.set_ticks_position("right")
                    axis.yaxis.set_label_position("right")
                    axis.set_yticklabels((r"$-\pi$", r"$y/L$", r"$\pi$"))
                    middle_label = axis.get_yticklabels()[1]
                    middle_label.set_rotation(90)
                    middle_label.set_horizontalalignment("center")
                    middle_label.set_verticalalignment("center")
                    middle_label.set_fontsize(9.0 * LAYOUT_SCALE)
                    middle_label.set_transform(
                        middle_label.get_transform()
                        + ScaledTranslation(
                            3.5 / 72.0,
                            0.0,
                            figure.dpi_scale_trans,
                        )
                    )

            if image is None:
                raise RuntimeError("No field panels were plotted.")
            row_images.append(
                (image, minimum, maximum, centered_on_one, int(vertical_mode))
            )

        for row_index, (
            image,
            minimum,
            maximum,
            centered_on_one,
            vertical_mode,
        ) in enumerate(row_images):
            panel_position = axes[row_index, -1].get_position()
            colorbar_axis = figure.add_axes(
                (
                    0.875,
                    panel_position.y0,
                    0.010,
                    panel_position.height,
                )
            )
            colorbar = figure.colorbar(
                image,
                cax=colorbar_axis,
                orientation="vertical",
            )
            if centered_on_one:
                colorbar.set_ticks((minimum, 1.0, maximum))
            else:
                colorbar.set_ticks(np.linspace(minimum, maximum, 3).tolist())
            if np.isclose(target_time, 50.0) and vertical_mode == 4:
                middle = round(0.5 * (minimum + maximum), 1)
                colorbar.set_ticks((minimum, middle, maximum))
                colorbar.ax.yaxis.set_major_formatter(
                    FuncFormatter(lambda value, _: colorbar_tick_label(value))
                )
            else:
                colorbar.ax.yaxis.set_major_formatter(
                    FuncFormatter(lambda value, _: colorbar_tick_label(value))
                )
            colorbar.ax.tick_params(
                length=2.0,
                width=0.5,
                pad=2.0,
                direction="out",
            )
            labels = colorbar.ax.get_yticklabels()
            if len(labels) >= 2:
                labels[0].set_verticalalignment("bottom")
                labels[-1].set_verticalalignment("top")
                labels[0].set_transform(
                    labels[0].get_transform()
                    + ScaledTranslation(
                        0.0,
                        -1.0 / 72.0,
                        figure.dpi_scale_trans,
                    )
                )
            colorbar.outline.set_linewidth(0.9)  # type: ignore[operator]

        top_position = axes[0, -1].get_position()
        figure.text(
            0.884,
            top_position.y1 + 0.006,
            r"$|\phi|^2$",
            va="bottom",
            ha="center",
            fontsize=10.0 * LAYOUT_SCALE,
        )

        output_stem.parent.mkdir(parents=True, exist_ok=True)
        figure_width, figure_height = figure.get_size_inches()
        export_box = Bbox.from_bounds(
            0.0,
            BOTTOM_CROP_INCHES,
            figure_width,
            figure_height - BOTTOM_CROP_INCHES,
        )
        figure.savefig(
            output_stem.with_suffix(".png"),
            dpi=600,
            bbox_inches=export_box,
        )
        figure.savefig(
            output_stem.with_suffix(".pdf"),
            dpi=600,
            bbox_inches=export_box,
        )
        plt.close(figure)
        metadata = {
            "schema_version": 1,
            "target_time_in_inertial_periods": target_time,
            "quantity": "normalised squared horizontal velocity",
            "model_names": [str(name) for name in model_names],
            "colormap": colormap_name,
            "color_limit_policy": {
                "quantiles": [0.005, 0.995],
                "outward_significant_digits": 3,
                "center_about_unity_when_lower_limit_is_at_least": 0.01,
                "published_override": {
                    "target_time_in_inertial_periods": 50.0,
                    "vertical_mode": 4,
                    "color_limits": list(PUBLISHED_N4_T50_LIMITS),
                },
            },
            "rows": color_rows,
        }
        output_stem.with_suffix(".json").write_text(
            json.dumps(metadata, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Plot sinusoidal-dipole wave-velocity fields."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument(
        "--output-directory",
        type=Path,
        default=DEFAULT_OUTPUT_DIRECTORY,
    )
    parser.add_argument("--colormap", default="twilight_shifted")
    parser.add_argument("--no-tex", action="store_true")
    return parser.parse_args()


def main() -> None:
    """Load the extracted fields and create one figure per saved time."""
    args = parse_args()
    with np.load(args.input) as data:
        times = data["times_in_inertial_periods"]
        vertical_modes = data["vertical_modes"]
        model_names = data["model_names"]
        squared_velocity = data["squared_velocity"]

    for time_index, target_time in enumerate(times):
        output_stem = args.output_directory / (
            f"sinusoidal_dipole_wave_velocity_{target_time:g}IP"
        )
        plot_snapshot(
            squared_velocity[time_index],
            vertical_modes,
            model_names,
            float(target_time),
            output_stem,
            colormap_name=args.colormap,
            use_tex=not args.no_tex,
        )
        print(output_stem.with_suffix(".png"))
        print(output_stem.with_suffix(".pdf"))
        print(output_stem.with_suffix(".json"))


if __name__ == "__main__":
    main()
