"""Plot the sinusoidal-dipole error statistics shown in Figure 8.

The script reads the CSV file generated by ``compute_error_statistics.py`` and
performs no processing of the original simulation files.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import matplotlib as mpl

mpl.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


DEFAULT_INPUT = (
    Path(__file__).resolve().parent / "data" / "sinusoidal_dipole_error_statistics.csv"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent / "figures" / "sinusoidal_dipole_error_statistics"
)

MODEL_STYLES = (
    ("YBJ", "YBJ", "#002BFF", "o", "-", 4.4, 3),
    ("TSB", "TSB", "#7A3E9D", "^", "--", 4.4, 5),
    (r"YBJ$^{+}$", "YBJ+", "#00C46A", "+", "-", 7.0, 6),
    ("PSE", "PSE", "#B2182B", "s", "-", 4.0, 9),
)
X_TICKS = [1, 4, 8, 12, 16, 20, 24, 28, 32]
FONT_SIZE = 10
STYLE_SCALE = 0.8


def publication_style() -> dict[str, object]:
    """Return the typography used for the published error figure."""
    scaled_font = FONT_SIZE * STYLE_SCALE
    return {
        "font.family": "serif",
        "font.serif": [
            "Times New Roman",
            "Times",
            "DejaVu Serif",
        ],
        "mathtext.fontset": "stix",
        "font.size": scaled_font,
        "axes.labelsize": scaled_font,
        "axes.titlesize": scaled_font,
        "xtick.labelsize": scaled_font,
        "ytick.labelsize": scaled_font,
        "legend.fontsize": scaled_font,
        "axes.linewidth": 1.0,
        "xtick.direction": "out",
        "ytick.direction": "out",
        "xtick.top": False,
        "ytick.right": False,
        "xtick.major.width": 0.8 * STYLE_SCALE,
        "ytick.major.width": 0.8 * STYLE_SCALE,
        "xtick.major.size": 2.8 * STYLE_SCALE,
        "ytick.major.size": 2.8 * STYLE_SCALE,
        "legend.frameon": True,
        "legend.fancybox": False,
        "legend.edgecolor": "black",
        "legend.framealpha": 1.0,
        "savefig.dpi": 600,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "savefig.facecolor": "white",
        "figure.facecolor": "white",
        "axes.facecolor": "white",
    }


def rounded_upper_limit(value: float) -> float:
    """Round an axis upper limit to a readable plotting interval."""
    if value <= 1:
        step = 0.2
    elif value <= 5:
        step = 1.0
    elif value <= 20:
        step = 5.0
    else:
        step = 10.0
    return max(step, step * math.ceil(value / step))


def plot_statistics(
    statistics: pd.DataFrame,
    output_stem: Path,
) -> None:
    """Create the two-panel error figure."""
    first_window = statistics[statistics["window"] == "0-10IP"]
    second_window = statistics[statistics["window"] == "0-50IP"]

    with plt.rc_context(publication_style()):
        figure, axes = plt.subplots(
            nrows=2,
            ncols=1,
            figsize=(5.6 * STYLE_SCALE, 4.3 * STYLE_SCALE),
            sharex=True,
            constrained_layout=False,
        )
        figure.subplots_adjust(
            left=0.15,
            right=0.85,
            top=0.82,
            bottom=0.10,
            hspace=0.20,
        )

        legend_handles = []
        legend_labels = []
        panels = (
            (axes[0], first_window, "0-10IP", "a"),
            (axes[1], second_window, "0-50IP", "b"),
        )
        for axis, frame, title, panel_label in panels:
            for (
                label,
                model,
                color,
                marker,
                linestyle,
                marker_size,
                zorder,
            ) in MODEL_STYLES:
                rows = frame[frame["model"] == model].sort_values("vertical_mode")
                (line,) = axis.plot(
                    rows["vertical_mode"],
                    rows["mean_error_percent"],
                    color=color,
                    marker=marker,
                    linestyle=linestyle,
                    linewidth=(
                        1.25 * STYLE_SCALE if marker == "+" else 1.1 * STYLE_SCALE
                    ),
                    markersize=marker_size * STYLE_SCALE,
                    markeredgewidth=(
                        1.25 * STYLE_SCALE if marker == "+" else 0.7 * STYLE_SCALE
                    ),
                    label=label,
                    zorder=zorder,
                )
                if axis is axes[0]:
                    legend_handles.append(line)
                    legend_labels.append(label)

            upper_limit = (
                4.0
                if axis is axes[0]
                else rounded_upper_limit(
                    float(frame["mean_error_percent"].max()) * 1.08
                )
            )
            axis.set_ylim(0.0, upper_limit)
            axis.set_xlim(0.7, 32.5)
            axis.set_xticks(X_TICKS)
            axis.grid(
                axis="y",
                color="0.78",
                linewidth=0.8 * STYLE_SCALE,
            )
            for spine in axis.spines.values():
                spine.set_zorder(20)
            axis.tick_params(zorder=21)
            axis.set_ylabel(r"$\overline{\mathrm{NRE}}$ (%)")
            axis.yaxis.set_label_coords(-0.075, 0.5)
            axis.text(
                0.5,
                0.915,
                title,
                transform=axis.transAxes,
                ha="center",
                va="top",
                clip_on=False,
            )
            axis.text(
                -0.13,
                1.02,
                rf"($\mathit{{{panel_label}}}$)",
                transform=axis.transAxes,
                ha="left",
                va="bottom",
                fontsize=10,
                clip_on=False,
            )

        axes[1].set_xlabel(r"Integer wavenumber $n$")
        figure.legend(
            legend_handles,
            legend_labels,
            loc="upper center",
            bbox_to_anchor=(0.5, 0.955),
            ncol=4,
            frameon=True,
            fancybox=False,
            edgecolor="black",
            framealpha=1.0,
            columnspacing=1.4,
            handlelength=2.2,
        )
        figure.legends[0].get_frame().set_linewidth(1.0)

        output_stem.parent.mkdir(parents=True, exist_ok=True)
        figure.savefig(output_stem.with_suffix(".png"))
        figure.savefig(output_stem.with_suffix(".pdf"))
        plt.close(figure)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Plot sinusoidal-dipole model-error statistics."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> None:
    """Load the statistics and create the error figure."""
    args = parse_args()
    statistics = pd.read_csv(args.input)
    plot_statistics(statistics, args.output)
    print(args.output.with_suffix(".png"))
    print(args.output.with_suffix(".pdf"))


if __name__ == "__main__":
    main()
