"""Plot the Gaussian-vortex spectrum shown in Figure 6.

The script reads the spectra generated by ``compute_eigenanalysis.py`` and
does not solve the radial eigenvalue problem.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib as mpl

mpl.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


FONT_SIZE = 10
DEFAULT_INPUT = (
    Path(__file__).resolve().parent / "data" / "gaussian_vortex_eigenanalysis.npz"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parent / "figures" / "gaussian_vortex_spectrum"
)
DEFAULT_COLORMAP = (
    Path(__file__).resolve().parent.parent / "common" / "custom_gradient_32_to_256.mat"
)


def publication_style(*, use_tex: bool) -> dict[str, object]:
    """Return the plotting style used for the eigenanalysis spectra."""
    scale = 0.8
    style: dict[str, object] = {
        "font.family": "serif",
        "font.size": FONT_SIZE * scale,
        "axes.labelsize": FONT_SIZE * scale,
        "axes.titlesize": FONT_SIZE * scale,
        "axes.linewidth": 1.2 * scale,
        "axes.unicode_minus": False,
        "xtick.labelsize": FONT_SIZE * scale,
        "ytick.labelsize": FONT_SIZE * scale,
        "xtick.direction": "out",
        "ytick.direction": "out",
        "xtick.major.size": 2.8 * scale,
        "ytick.major.size": 2.8 * scale,
        "xtick.major.width": 1.2 * scale,
        "ytick.major.width": 1.2 * scale,
        "legend.fontsize": FONT_SIZE * scale,
        "savefig.dpi": 600,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
    if use_tex:
        style.update(
            {
                "text.usetex": True,
                "text.latex.preamble": (
                    r"\usepackage{amsmath}"
                    r"\usepackage{newtxtext}"
                    r"\usepackage{newtxmath}"
                ),
            }
        )
    else:
        style.update({"text.usetex": False, "mathtext.fontset": "stix"})
    return style


def load_colormap(path: Path) -> mpl.colors.ListedColormap:
    """Load the colour gradient used in the published spectrum."""
    import h5py

    with h5py.File(path, "r") as file:
        colors = np.asarray(file["C"], dtype=float)
    if colors.shape[0] == 3:
        colors = colors.T
    colors = np.clip(0.88 * colors[::-1], 0.0, 1.0)

    transition_size = 52
    gray_weight = 0.65 * (1.0 - np.linspace(0.0, 1.0, transition_size)) ** 1.4
    gray = colors[:transition_size].mean(axis=1, keepdims=True)
    colors[:transition_size] = (
        gray_weight[:, None] * gray
        + (1.0 - gray_weight[:, None]) * colors[:transition_size]
    )
    return mpl.colors.ListedColormap(colors, name="custom_gradient")


def five_lowest_modes(data: np.ndarray) -> np.ndarray:
    """Return the five lowest displayed modes at each scan coordinate."""
    return np.vstack(
        [
            group[np.argsort(group[:, 2])][:5]
            for coordinate in np.unique(data[:, 0])
            for group in [data[np.isclose(data[:, 0], coordinate)]]
        ]
    )


def scatter_by_branch(
    axis: mpl.axes.Axes,
    data: np.ndarray,
    style: dict[str, object],
) -> mpl.collections.PathCollection:
    """Draw high-frequency branches first so lower branches remain visible."""
    collection: mpl.collections.PathCollection | None = None
    for branch in sorted(
        np.unique(data[:, 1]).astype(int),
        reverse=True,
    ):
        branch_data = data[data[:, 1] == branch]
        collection = axis.scatter(
            branch_data[:, 0],
            branch_data[:, 2],
            c=branch_data[:, 4],
            **style,
        )
    if collection is None:
        raise ValueError("No spectrum points are available for plotting.")
    return collection


def plot_spectrum(
    vertical_mode_rows: np.ndarray,
    azimuthal_rows: np.ndarray,
    output_stem: Path,
    *,
    colormap_path: Path,
    vertical_frequency_min: float,
    vertical_frequency_max: float,
    azimuthal_frequency_min: float,
    azimuthal_frequency_max: float,
    ratio_min: float,
    ratio_max: float,
    fixed_azimuthal_wavenumber: int,
    fixed_vertical_mode: int,
    use_tex: bool,
) -> None:
    """Create the two-panel Gaussian-vortex spectrum figure."""
    vertical_data = vertical_mode_rows[
        (vertical_mode_rows[:, 2] >= vertical_frequency_min)
        & (vertical_mode_rows[:, 2] <= vertical_frequency_max)
    ]
    azimuthal_data = azimuthal_rows[
        (azimuthal_rows[:, 2] >= azimuthal_frequency_min)
        & (azimuthal_rows[:, 2] <= azimuthal_frequency_max)
    ]
    selected_vertical = five_lowest_modes(vertical_data)
    selected_azimuthal = five_lowest_modes(azimuthal_data)

    scale = 0.8
    with plt.rc_context(publication_style(use_tex=use_tex)):
        figure = plt.figure(figsize=(5.6 * scale, 4.3 * scale))
        colorbar_axis = figure.add_axes([0.905, 0.15, 0.014, 0.72])
        vertical_axis = figure.add_axes([0.16, 0.58, 0.72, 0.34])
        azimuthal_axis = figure.add_axes([0.16, 0.10, 0.72, 0.34])

        colormap = load_colormap(colormap_path)
        normalization = mpl.colors.Normalize(
            vmin=ratio_min,
            vmax=ratio_max,
            clip=True,
        )
        point_style: dict[str, object] = {
            "s": 12.5 * scale**2,
            "linewidths": 0.35 * scale,
            "edgecolors": "black",
            "cmap": colormap,
            "norm": normalization,
            "rasterized": True,
        }
        faint_style = point_style | {
            "linewidths": 0.0,
            "edgecolors": "none",
            "alpha": 0.16,
        }

        scatter_by_branch(vertical_axis, vertical_data, faint_style)
        vertical_axis.axhline(
            0.0,
            color="0.55",
            linewidth=0.7 * scale,
            zorder=0,
        )
        vertical_axis.set(
            xlim=(0.4, 32.6),
            ylim=(vertical_frequency_min, vertical_frequency_max),
            xlabel=r"Integer wavenumber $n$",
            ylabel=r"$\omega/f$",
        )
        maximum_tick = 4 * int(np.ceil(vertical_mode_rows[:, 0].max() / 4))
        mode_ticks = np.r_[0, 1, np.arange(4, maximum_tick + 1, 4)]
        vertical_axis.set_xticks(mode_ticks)
        vertical_axis.set_xticklabels([""] + [rf"${tick}$" for tick in mode_ticks[1:]])
        vertical_axis.set_yticks(
            np.arange(
                vertical_frequency_min,
                vertical_frequency_max + 0.1,
                0.2,
            )
        )
        vertical_axis.axvline(
            fixed_vertical_mode,
            color="0.25",
            linewidth=0.8 * scale,
            linestyle="--",
            zorder=0.2,
        )
        scatter_by_branch(
            vertical_axis,
            selected_vertical,
            point_style | {"zorder": 5, "clip_on": True},
        )
        vertical_axis.text(
            -0.135,
            1.025,
            r"$(a)$",
            transform=vertical_axis.transAxes,
            ha="left",
            va="bottom",
            clip_on=False,
        )

        scatter_by_branch(azimuthal_axis, azimuthal_data, faint_style)
        azimuthal_axis.axhline(
            0.0,
            color="0.55",
            linewidth=0.7 * scale,
            zorder=0,
        )
        azimuthal_axis.set(
            xlim=(-16.4, 16.4),
            ylim=(azimuthal_frequency_min, azimuthal_frequency_max),
            xlabel=r"Azimuthal wavenumber $\ell$",
            ylabel=r"$\omega/f$",
        )
        azimuthal_ticks = np.arange(-16, 17, 4)
        azimuthal_axis.set_xticks(azimuthal_ticks)
        azimuthal_axis.set_xticklabels([rf"${tick}$" for tick in azimuthal_ticks])
        azimuthal_axis.set_yticks(
            np.arange(
                azimuthal_frequency_min,
                azimuthal_frequency_max + 0.1,
                0.2,
            )
        )
        scatter_by_branch(
            azimuthal_axis,
            selected_azimuthal,
            point_style | {"zorder": 5, "clip_on": True},
        )
        azimuthal_axis.axvline(
            fixed_azimuthal_wavenumber,
            color="0.25",
            linewidth=0.8 * scale,
            linestyle="--",
            zorder=0.2,
        )
        azimuthal_axis.text(
            -0.135,
            1.025,
            r"$(b)$",
            transform=azimuthal_axis.transAxes,
            ha="left",
            va="bottom",
            clip_on=False,
        )

        color_scale = mpl.cm.ScalarMappable(
            norm=normalization,
            cmap=colormap,
        )
        color_scale.set_array([])
        colorbar = figure.colorbar(
            color_scale,
            cax=colorbar_axis,
            orientation="vertical",
        )
        colorbar_ticks = np.linspace(ratio_min, ratio_max, 5)
        colorbar.set_ticks(colorbar_ticks)
        colorbar.set_ticklabels([rf"${tick:.2g}$" for tick in colorbar_ticks])
        colorbar.ax.tick_params(direction="out", pad=2 * scale)
        colorbar.ax.set_ylabel(
            r"Averaged ratio "
            r"$|\mathscr{A}_{\downarrow}|/|\mathscr{A}_{\uparrow}|$",
            rotation=90,
            labelpad=8 * scale,
            va="center",
        )

        output_stem.parent.mkdir(parents=True, exist_ok=True)
        figure.savefig(
            output_stem.with_suffix(".png"),
            bbox_inches="tight",
            pad_inches=0.02,
        )
        figure.savefig(
            output_stem.with_suffix(".pdf"),
            bbox_inches="tight",
            pad_inches=0.02,
        )
        plt.close(figure)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Plot the Gaussian-vortex eigenvalue spectrum."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--colormap", type=Path, default=DEFAULT_COLORMAP)
    parser.add_argument("--vertical-frequency-min", type=float, default=-0.5)
    parser.add_argument("--vertical-frequency-max", type=float, default=0.5)
    parser.add_argument("--azimuthal-frequency-min", type=float, default=-0.5)
    parser.add_argument("--azimuthal-frequency-max", type=float, default=0.5)
    parser.add_argument("--ratio-min", type=float, default=0.0)
    parser.add_argument("--ratio-max", type=float, default=0.4)
    parser.add_argument("--fixed-azimuthal-wavenumber", type=int, default=0)
    parser.add_argument("--fixed-vertical-mode", type=int, default=4)
    parser.add_argument("--no-tex", action="store_true")
    return parser.parse_args()


def main() -> None:
    """Load the computed data and create the spectrum figure."""
    args = parse_args()
    with np.load(args.input) as data:
        vertical_mode_rows = data["vertical_mode_spectrum"]
        azimuthal_rows = data["azimuthal_spectrum"]
    plot_spectrum(
        vertical_mode_rows,
        azimuthal_rows,
        args.output,
        colormap_path=args.colormap,
        vertical_frequency_min=args.vertical_frequency_min,
        vertical_frequency_max=args.vertical_frequency_max,
        azimuthal_frequency_min=args.azimuthal_frequency_min,
        azimuthal_frequency_max=args.azimuthal_frequency_max,
        ratio_min=args.ratio_min,
        ratio_max=args.ratio_max,
        fixed_azimuthal_wavenumber=args.fixed_azimuthal_wavenumber,
        fixed_vertical_mode=args.fixed_vertical_mode,
        use_tex=not args.no_tex,
    )
    print(args.output.with_suffix(".png"))
    print(args.output.with_suffix(".pdf"))


if __name__ == "__main__":
    main()
